### ISSUE TITLE
Add PAT authentication

### ISSUE THREAD

**Issue by chimon2000** [djedje72/azure-devops-chrome-extension#19]
For more granular permissions, it would be nice if PAT authentication was supported.

**Comment by djedje72** [comment]
Hello, it was PAT authentication before. I'll look if i have time to add  a way to choice between PAT and Oauth.

**Comment by chimon2000** [comment]
Some organizations only allow certain types of authentication. Mine for example doesn't allow oath but they do allow access tokens.

**Comment by djedje72** [comment]
Extension is waiting for approval by Google. I'll sent you an update when it's OK ! 
If you want, you can send me an email and i can send you the unpacked extension if you want to try it !
Thanks for your issue ;)

**Comment by djedje72** [comment]
You can also use the dist folder as unpacked extension if you git clone and start this repo 😀

**Comment by djedje72** [comment]
@chimon2000 The extension is up to date : "https://chrome.google.com/webstore/detail/azure-devops-pull-request/pbjkodijnlbkbbkjmhgemlpigeaoaken?hl=fr"
Can you confirm PAT is ok ? 😄

**Comment by chimon2000** [comment]
Yup, works like a charm @djedje72
